name: robust_web
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - numpy==1.21.5
  - matplotlib==3.2.2
  - pandas==1.3.5
  - pip
  - jupyter
  - mygene==3.2.2
  - ndex2==3.5.0
  - networkx==2.6.3
  - pcst-fast==1.0.7
  - shortuuid==1.0.9
  - WTForms==3.0.1
  - rq==1.11.1
  - importlib-metadata==4.13.0
  - seaborn==0.11.2
  - redis==4.3.4
  - Flask_WTF==1.0.1
  - celery==5.2.7
  - Flask==2.1.2
  - Flask_APScheduler==1.12.4
  - Flask_SQLAlchemy==2.5.1

