name: robust
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - numpy==1.21.5
  - matplotlib==3.2.2
  - pandas==1.3.5
  - pip
  - jupyter
  - mygene==3.2.2
  - ndex2==3.5.0
  - networkx==2.6.3
  - requests==2.28.1
  - ipycytoscape==1.0.4
  - ipywidgets==7.5.1
  - pcst-fast==1.0.7
